name: 'Validate and Scan Terraform code'

on:
  push:
    branches: [ "main" ]
  pull_request:

  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  static_analysis:
    name: Validate and Scan Terraform code
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4.1.0

      - name: TFSec PR commenter
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}

      - name: Run TFSec
        uses: aquasecurity/tfsec-action@v1.0.0
        # with:
        #   soft_fail: false

      - name: Check TFSec issues
        if: ${{ failure() }}
        run: exit 1

  code_review_approve:
    name: Code review and approve
    runs-on: ubuntu-latest
    needs: static_analysis
    steps:
      - uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          secret: ${{ github.TOKEN }}
          approvers: oleksii-bebych
          minimum-approvals: 1

  integration_test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: code_review_approve
    steps:
      - name: Deploy to Production
        run: echo "Deployment steps go here"


